spring.application.name=AsteroidAlertNotificationService
server.port=8081

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/asteroidcollisionalerts
spring.datasource.username=postgres
spring.datasource.password=unknownfuture23!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=AsteroidCollisionEvent
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.AsteroidCollisionAlert.event


# MailTrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=27d3de7f66bbf1
spring.mail.password=64e36e87d33761
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

email.sender=hikikomorinel@gmail.com
