spring.application.name=asteroidalert

nasa.neo.api.url=https://api.nasa.gov/neo/rest/v1/feed
nasa.api.key=Ol1fzKJKQ5zUPGTSykItDes9fBMylFVMRoWeUMRS

#Kafka
spring.kafka.bootstrap-servers=local:9892
spring.kafka.template.default-topic=asteroid-alert
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
